[build]
  command = "npm run build"
  publish = "dist/app/browser"

[functions]
  directory = "dist/app/server"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist/app/browser"
